import { Ionicons } from "@expo/vector-icons";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { formatCreditDate, getCreditPresentation } from "../../../../../features/payments/CreditTransactionRow";
import { formatLkr } from "../../../../../features/payments/paymentTheme";
import { creditService } from "../../../../../services/payments/creditService";
import type { PickuCreditTransaction } from "../../../../../services/payments/creditTypes";

export default function WalletTransactionDetail() {
  const { id } = useLocalSearchParams<{ id: string }>(); const insets = useSafeAreaInsets(); const [item, setItem] = useState<PickuCreditTransaction | null>(null); const [error, setError] = useState("");
  useEffect(() => { let active = true; void creditService.getTransaction(String(id)).then((result) => { if (!active) return; if (result.success && result.data) setItem(result.data); else setError(result.message || "Transaction unavailable."); }); return () => { active = false; }; }, [id]);
  const view = item ? getCreditPresentation(item) : null;
  return <View style={[styles.screen, { paddingTop: insets.top + 8 }]}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" size={22} color="#063D31" /></TouchableOpacity><Text style={styles.headerTitle}>Transaction details</Text><View style={styles.space} /></View><ScrollView contentContainerStyle={styles.content}>{!item && !error ? <ActivityIndicator style={styles.loader} color="#067A50" /> : error ? <View style={styles.error}><Ionicons name="alert-circle-outline" size={34} color="#9A5B06" /><Text style={styles.errorTitle}>Transaction unavailable</Text><Text style={styles.errorText}>{error}</Text></View> : item && view ? <><View style={styles.hero}><View style={styles.heroIcon}><Ionicons name={view.icon} size={28} color="#067A50" /></View><Text style={styles.heroTitle}>{view.title}</Text><Text style={styles.amount}>{view.sign}{formatLkr(item.amount)}</Text><View style={styles.status}><Text style={styles.statusText}>{item.status}</Text></View></View><View style={styles.details}><Row label="Status" value={item.status} /><Row label="Date" value={formatCreditDate(item.createdAt, true)} /><Row label="Reference" value={item.reference || "Not available"} />{item.balanceAfter !== null ? <Row label="Balance after" value={formatLkr(item.balanceAfter)} /> : null}<Row label="Reason" value={item.reason || view.title} /></View></> : null}</ScrollView></View>;
}
function Row({ label, value }: { label: string; value: string }) { return <View style={styles.row}><Text style={styles.label}>{label}</Text><Text style={styles.value} selectable>{value}</Text></View>; }
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#F2FBF8" }, header: { height: 52, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16 }, back: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#DDEBE6" }, headerTitle: { color: "#18231F", fontSize: 18, fontWeight: "900" }, space: { width: 40 }, content: { padding: 18, paddingBottom: 80, flexGrow: 1 }, loader: { flex: 1 }, hero: { backgroundColor: "#FFFFFF", borderRadius: 24, alignItems: "center", padding: 24, borderWidth: 1, borderColor: "#DCE9E4" }, heroIcon: { width: 58, height: 58, borderRadius: 20, backgroundColor: "#E4F8EF", alignItems: "center", justifyContent: "center" }, heroTitle: { color: "#44544E", fontSize: 14, fontWeight: "800", marginTop: 13 }, amount: { color: "#18231F", fontSize: 28, fontWeight: "900", marginTop: 5 }, status: { marginTop: 12, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: "#E4F8EF", borderRadius: 10 }, statusText: { color: "#067A50", fontSize: 10, fontWeight: "900" }, details: { marginTop: 16, backgroundColor: "rgba(255,255,255,.72)", borderRadius: 22, paddingHorizontal: 16, borderWidth: 1, borderColor: "#DCE9E4" }, row: { minHeight: 62, flexDirection: "row", alignItems: "center", gap: 16, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: "#DCE9E4" }, label: { width: 95, color: "#71817B", fontSize: 12, fontWeight: "700" }, value: { flex: 1, color: "#25342F", fontSize: 13, lineHeight: 18, fontWeight: "800", textAlign: "right" }, error: { flex: 1, alignItems: "center", justifyContent: "center" }, errorTitle: { color: "#25342F", fontSize: 17, fontWeight: "900", marginTop: 10 }, errorText: { color: "#71817B", fontSize: 12, textAlign: "center", marginTop: 6 } });
