import { Ionicons } from "@expo/vector-icons";
import { Alert, Linking, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import RideScreenShell, { RideCard, SecondaryRideButton } from "../../features/ride-support/RideScreenShell";
import { rideTheme } from "../../features/ride-support/rideUtils";

export default function RideSafetyScreen() {
  return (
    <RideScreenShell title="Safety" subtitle="Quick actions while your ride is active.">
      <RideCard>
        <TouchableOpacity style={styles.sos} onPress={() => Alert.alert("SOS", "Emergency contact integration can be connected here.")} activeOpacity={0.85}>
          <Ionicons name="warning" size={28} color="#FFFFFF" />
          <View style={{ flex: 1 }}><Text style={styles.sosTitle}>Emergency SOS</Text><Text style={styles.sosSub}>Alert support or emergency contacts</Text></View>
        </TouchableOpacity>
      </RideCard>
      <SecondaryRideButton label="Share trip" icon="share-social-outline" onPress={() => Alert.alert("Share trip", "Live trip share link can be generated by backend later.")} />
      <SecondaryRideButton label="Call emergency" icon="call-outline" danger onPress={() => Linking.openURL("tel:119")} />
      <RideCard><Text style={styles.note}>Tip: confirm the vehicle number before entering and keep your route visible during the trip.</Text></RideCard>
    </RideScreenShell>
  );
}

const styles = StyleSheet.create({
  sos: { minHeight: 88, borderRadius: 18, backgroundColor: rideTheme.danger, flexDirection: "row", alignItems: "center", gap: 14, padding: 16 },
  sosTitle: { color: "#FFFFFF", fontSize: 18, fontWeight: "900" },
  sosSub: { color: "rgba(255,255,255,0.82)", marginTop: 3, fontSize: 12 },
  note: { color: rideTheme.muted, lineHeight: 20, fontWeight: "700" },
});