import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useCallback, useEffect, useState } from "react";
import { ActivityIndicator, FlatList, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import CreditTransactionRow from "../../../../features/payments/CreditTransactionRow";
import { creditService } from "../../../../services/payments/creditService";
import type { PickuCreditTransaction } from "../../../../services/payments/creditTypes";

export default function WalletTransactionsScreen() {
  const insets = useSafeAreaInsets(); const [items, setItems] = useState<PickuCreditTransaction[]>([]); const [page, setPage] = useState(1); const [lastPage, setLastPage] = useState(1); const [loading, setLoading] = useState(true); const [more, setMore] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async (nextPage = 1) => { if (nextPage === 1) setLoading(true); else setMore(true); const result = await creditService.getSummary(nextPage); if (result.success && result.data) { setItems((current) => nextPage === 1 ? result.data!.transactions : [...current, ...result.data!.transactions.filter((entry) => !current.some((old) => old.id === entry.id))]); setPage(result.data.pagination.currentPage); setLastPage(result.data.pagination.lastPage); setError(""); } else setError(result.message || "Couldn’t load activity."); setLoading(false); setMore(false); }, []);
  useEffect(() => { void load(); }, [load]);
  return <View style={[styles.screen, { paddingTop: insets.top + 8 }]}><View style={styles.header}><TouchableOpacity style={styles.back} onPress={() => router.back()}><Ionicons name="arrow-back" size={22} color="#063D31" /></TouchableOpacity><Text style={styles.title}>Credit activity</Text><View style={styles.space} /></View>{loading ? <ActivityIndicator style={styles.loader} color="#067A50" /> : <FlatList data={items} keyExtractor={(item) => String(item.id)} contentContainerStyle={styles.content} renderItem={({ item }) => <CreditTransactionRow transaction={item} onPress={() => router.push(`/(app)/(tabs)/account/wallet-transaction/${item.id}` as any)} />} onRefresh={() => void load(1)} refreshing={loading} onEndReached={() => { if (!more && page < lastPage) void load(page + 1); }} onEndReachedThreshold={.35} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyTitle}>{error ? "Couldn’t load activity" : "No credit activity yet"}</Text><Text style={styles.emptyText}>{error || "Your PickU credit activity will appear here."}</Text>{error ? <TouchableOpacity style={styles.retry} onPress={() => void load(1)}><Text style={styles.retryText}>Try again</Text></TouchableOpacity> : null}</View>} ListFooterComponent={more ? <ActivityIndicator style={styles.footer} color="#067A50" /> : error && items.length ? <TouchableOpacity style={styles.footer} onPress={() => void load(page + 1)}><Text style={styles.retryLink}>Couldn’t load more · Retry</Text></TouchableOpacity> : null} />}</View>;
}
const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: "#F2FBF8" }, header: { height: 52, flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16 }, back: { width: 40, height: 40, borderRadius: 20, backgroundColor: "#FFFFFF", alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: "#DDEBE6" }, title: { color: "#18231F", fontSize: 18, fontWeight: "900" }, space: { width: 40 }, content: { margin: 18, paddingHorizontal: 15, paddingBottom: 90, backgroundColor: "rgba(255,255,255,.72)", borderRadius: 22, borderWidth: 1, borderColor: "#DCE9E4", flexGrow: 1 }, loader: { flex: 1 }, empty: { flex: 1, minHeight: 250, alignItems: "center", justifyContent: "center", padding: 25 }, emptyTitle: { color: "#25342F", fontSize: 16, fontWeight: "900" }, emptyText: { color: "#71817B", fontSize: 12, lineHeight: 18, textAlign: "center", marginTop: 6 }, retry: { padding: 12, marginTop: 12 }, retryText: { color: "#067A50", fontWeight: "900" }, footer: { paddingVertical: 20, alignItems: "center" }, retryLink: { color: "#9A5B06", fontSize: 12, fontWeight: "800" } });
